"""loans and loan payments

Revision ID: ba350553c3a4
Revises: 33cc63580cdb
Create Date: 2026-08-21 09:14:45.592909
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'ba350553c3a4'
down_revision: str | None = '33cc63580cdb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lender_id', sa.UUID(), nullable=False),
    sa.Column('borrower_name', sa.String(length=120), nullable=False),
    sa.Column('borrower_user_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_loans_amount_is_positive')),
    sa.CheckConstraint('lender_id <> borrower_user_id', name=op.f('ck_loans_no_loan_to_yourself')),
    sa.ForeignKeyConstraint(['borrower_user_id'], ['users.id'], name=op.f('fk_loans_borrower_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lender_id'], ['users.id'], name=op.f('fk_loans_lender_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loans'))
    )
    op.create_index(op.f('ix_loans_borrower_user_id'), 'loans', ['borrower_user_id'], unique=False)
    op.create_index(op.f('ix_loans_due_date'), 'loans', ['due_date'], unique=False)
    op.create_index('ix_loans_lender_due', 'loans', ['lender_id', 'due_date'], unique=False)
    op.create_index(op.f('ix_loans_lender_id'), 'loans', ['lender_id'], unique=False)
    op.create_table('loan_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_loan_payments_amount_is_positive')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_loan_payments_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name=op.f('fk_loan_payments_loan_id_loans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loan_payments'))
    )
    op.create_index('ix_loan_payments_loan_date', 'loan_payments', ['loan_id', 'payment_date'], unique=False)
    op.create_index(op.f('ix_loan_payments_loan_id'), 'loan_payments', ['loan_id'], unique=False)
    op.create_index(op.f('ix_loan_payments_payment_date'), 'loan_payments', ['payment_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loan_payments_payment_date'), table_name='loan_payments')
    op.drop_index(op.f('ix_loan_payments_loan_id'), table_name='loan_payments')
    op.drop_index('ix_loan_payments_loan_date', table_name='loan_payments')
    op.drop_table('loan_payments')
    op.drop_index(op.f('ix_loans_lender_id'), table_name='loans')
    op.drop_index('ix_loans_lender_due', table_name='loans')
    op.drop_index(op.f('ix_loans_due_date'), table_name='loans')
    op.drop_index(op.f('ix_loans_borrower_user_id'), table_name='loans')
    op.drop_table('loans')
    # ### end Alembic commands ###
