"""notifications

Revision ID: a4d2e2a8401d
Revises: d2beaf1c4401
Create Date: 2026-09-23 13:41:52.295327
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'a4d2e2a8401d'
down_revision: str | None = 'd2beaf1c4401'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('expense_added', 'expense_updated', 'expense_deleted', 'settlement_recorded', 'settlement_updated', 'settlement_deleted', 'friend_request', 'friend_accepted', 'group_added', 'group_removed', 'group_role_changed', 'group_ownership_transferred', 'group_deleted', 'invitation_accepted', name='notificationtype', native_enum=False, length=40), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_notifications_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_notifications_recipient_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_recipient_created', 'notifications', ['recipient_id', 'created_at'], unique=False)
    op.create_index('ix_notifications_recipient_unread', 'notifications', ['recipient_id'], unique=False, postgresql_where='read_at IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_recipient_unread', table_name='notifications', postgresql_where='read_at IS NULL')
    op.drop_index('ix_notifications_recipient_created', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
