"""notes and reminders

Revision ID: da15337b2ebf
Revises: ba350553c3a4
Create Date: 2026-08-21 09:35:16.897792
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'da15337b2ebf'
down_revision: str | None = 'ba350553c3a4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('khata_id', sa.UUID(), nullable=True),
    sa.Column('loan_id', sa.UUID(), nullable=True),
    sa.Column('person_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(CASE WHEN khata_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN loan_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN person_user_id IS NOT NULL THEN 1 ELSE 0 END) = 1', name=op.f('ck_notes_exactly_one_subject')),
    sa.CheckConstraint('length(btrim(body)) > 0', name=op.f('ck_notes_body_is_not_blank')),
    sa.ForeignKeyConstraint(['khata_id'], ['khata_accounts.id'], name=op.f('fk_notes_khata_id_khata_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name=op.f('fk_notes_loan_id_loans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_notes_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_user_id'], ['users.id'], name=op.f('fk_notes_person_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_index(op.f('ix_notes_khata_id'), 'notes', ['khata_id'], unique=False)
    op.create_index(op.f('ix_notes_loan_id'), 'notes', ['loan_id'], unique=False)
    op.create_index('ix_notes_owner_created', 'notes', ['owner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notes_owner_id'), 'notes', ['owner_id'], unique=False)
    op.create_index(op.f('ix_notes_person_user_id'), 'notes', ['person_user_id'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('remind_on', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('khata_id', sa.UUID(), nullable=True),
    sa.Column('loan_id', sa.UUID(), nullable=True),
    sa.Column('person_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(CASE WHEN khata_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN loan_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN person_user_id IS NOT NULL THEN 1 ELSE 0 END) = 1', name=op.f('ck_reminders_exactly_one_subject')),
    sa.CheckConstraint('amount IS NULL OR amount > 0', name=op.f('ck_reminders_amount_is_positive')),
    sa.CheckConstraint('length(btrim(title)) > 0', name=op.f('ck_reminders_title_is_not_blank')),
    sa.CheckConstraint('remind_on IS NULL OR remind_on <= due_date', name=op.f('ck_reminders_remind_on_before_due_date')),
    sa.ForeignKeyConstraint(['khata_id'], ['khata_accounts.id'], name=op.f('fk_reminders_khata_id_khata_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name=op.f('fk_reminders_loan_id_loans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_reminders_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_user_id'], ['users.id'], name=op.f('fk_reminders_person_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminders'))
    )
    op.create_index(op.f('ix_reminders_due_date'), 'reminders', ['due_date'], unique=False)
    op.create_index(op.f('ix_reminders_khata_id'), 'reminders', ['khata_id'], unique=False)
    op.create_index(op.f('ix_reminders_loan_id'), 'reminders', ['loan_id'], unique=False)
    op.create_index('ix_reminders_owner_due', 'reminders', ['owner_id', 'due_date'], unique=False)
    op.create_index(op.f('ix_reminders_owner_id'), 'reminders', ['owner_id'], unique=False)
    op.create_index(op.f('ix_reminders_person_user_id'), 'reminders', ['person_user_id'], unique=False)
    op.create_index(op.f('ix_reminders_remind_on'), 'reminders', ['remind_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminders_remind_on'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_person_user_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_owner_id'), table_name='reminders')
    op.drop_index('ix_reminders_owner_due', table_name='reminders')
    op.drop_index(op.f('ix_reminders_loan_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_khata_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_due_date'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_notes_person_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_owner_id'), table_name='notes')
    op.drop_index('ix_notes_owner_created', table_name='notes')
    op.drop_index(op.f('ix_notes_loan_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_khata_id'), table_name='notes')
    op.drop_table('notes')
    # ### end Alembic commands ###
