"""add settlements

Revision ID: ceed727e5235
Revises: f3309a5e9d86
Create Date: 2026-08-19 14:49:39.924026
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'ceed727e5235'
down_revision: str | None = 'f3309a5e9d86'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('from_user_id', sa.UUID(), nullable=False),
    sa.Column('to_user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('settled_on', sa.Date(), nullable=False),
    sa.Column('method', sa.Enum('cash', 'bank_transfer', 'card', 'paypal', 'venmo', 'upi', 'other', name='paymentmethod', native_enum=False, length=24), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_settlements_amount_is_positive')),
    sa.CheckConstraint('from_user_id <> to_user_id', name=op.f('ck_settlements_no_self_settlement')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_settlements_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name=op.f('fk_settlements_from_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_settlements_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], name=op.f('fk_settlements_to_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlements'))
    )
    op.create_index(op.f('ix_settlements_from_user_id'), 'settlements', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_settlements_group_id'), 'settlements', ['group_id'], unique=False)
    op.create_index('ix_settlements_pair', 'settlements', ['from_user_id', 'to_user_id'], unique=False)
    op.create_index(op.f('ix_settlements_settled_on'), 'settlements', ['settled_on'], unique=False)
    op.create_index(op.f('ix_settlements_to_user_id'), 'settlements', ['to_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settlements_to_user_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_settled_on'), table_name='settlements')
    op.drop_index('ix_settlements_pair', table_name='settlements')
    op.drop_index(op.f('ix_settlements_group_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_from_user_id'), table_name='settlements')
    op.drop_table('settlements')
    # ### end Alembic commands ###
