"""add performance indexes

Revision ID: d963c1ca1c91
Revises: ceed727e5235
Create Date: 2026-08-19 15:33:24.826392
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'd963c1ca1c91'
down_revision: str | None = 'ceed727e5235'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_expense_splits_user_amount', 'expense_splits', ['user_id', 'amount'], unique=False)
    op.create_index('ix_expenses_currency_date', 'expenses', ['currency', 'expense_date'], unique=False)
    op.create_index('ix_expenses_group_date', 'expenses', ['group_id', 'expense_date'], unique=False)
    op.create_index('ix_group_members_user_group', 'group_members', ['user_id', 'group_id'], unique=False)
    op.create_index('ix_settlements_group_date', 'settlements', ['group_id', 'settled_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_settlements_group_date', table_name='settlements')
    op.drop_index('ix_group_members_user_group', table_name='group_members')
    op.drop_index('ix_expenses_group_date', table_name='expenses')
    op.drop_index('ix_expenses_currency_date', table_name='expenses')
    op.drop_index('ix_expense_splits_user_amount', table_name='expense_splits')
    # ### end Alembic commands ###
