"""add khata accounts and entries

Revision ID: f192e574e586
Revises: d963c1ca1c91
Create Date: 2026-08-20 14:21:12.654570
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f192e574e586'
down_revision: str | None = 'd963c1ca1c91'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('khata_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('person_name', sa.String(length=120), nullable=False),
    sa.Column('person_user_id', sa.UUID(), nullable=True),
    sa.Column('person_phone', sa.String(length=32), nullable=True),
    sa.Column('person_email', sa.String(length=320), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('owner_id <> person_user_id', name=op.f('ck_khata_accounts_no_khata_with_yourself')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_khata_accounts_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_user_id'], ['users.id'], name=op.f('fk_khata_accounts_person_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_khata_accounts'))
    )
    op.create_index('ix_khata_accounts_owner_archived', 'khata_accounts', ['owner_id', 'is_archived'], unique=False)
    op.create_index(op.f('ix_khata_accounts_owner_id'), 'khata_accounts', ['owner_id'], unique=False)
    op.create_index(op.f('ix_khata_accounts_person_user_id'), 'khata_accounts', ['person_user_id'], unique=False)
    op.create_index('uq_khata_accounts_owner_person', 'khata_accounts', ['owner_id', 'person_user_id'], unique=True, postgresql_where=sa.text('person_user_id IS NOT NULL'))
    op.create_table('khata_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('khata_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.Enum('given', 'received', name='khataentrytype', native_enum=False, length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_khata_entries_amount_is_positive')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_khata_entries_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['khata_id'], ['khata_accounts.id'], name=op.f('fk_khata_entries_khata_id_khata_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_khata_entries'))
    )
    op.create_index(op.f('ix_khata_entries_entry_date'), 'khata_entries', ['entry_date'], unique=False)
    op.create_index('ix_khata_entries_khata_date', 'khata_entries', ['khata_id', 'entry_date'], unique=False)
    op.create_index(op.f('ix_khata_entries_khata_id'), 'khata_entries', ['khata_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_khata_entries_khata_id'), table_name='khata_entries')
    op.drop_index('ix_khata_entries_khata_date', table_name='khata_entries')
    op.drop_index(op.f('ix_khata_entries_entry_date'), table_name='khata_entries')
    op.drop_table('khata_entries')
    op.drop_index('uq_khata_accounts_owner_person', table_name='khata_accounts', postgresql_where=sa.text('person_user_id IS NOT NULL'))
    op.drop_index(op.f('ix_khata_accounts_person_user_id'), table_name='khata_accounts')
    op.drop_index(op.f('ix_khata_accounts_owner_id'), table_name='khata_accounts')
    op.drop_index('ix_khata_accounts_owner_archived', table_name='khata_accounts')
    op.drop_table('khata_accounts')
    # ### end Alembic commands ###
